schema:
  - "http://localhost:4000/api"
documents: ./src/**/*.graphql
extensions:
  codegen:
    generates:
      ./src/generated-frontend.ts:
        plugins:
          - typescript
          - typescript-operations
          - typescript-react-apollo
