version: "3"
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - backend

  backend:
    container_name: backend
    build:
      context: ./backend
    environment:
      MIX_ENV: dev
    ports:
      - 4000:4000
    volumes:
      - ./backend:/usr/src/app
